# Generated by Django 4.1.3 on 2022-12-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('price', models.FloatField()),
                ('link', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
