# Generated by Django 4.1.3 on 2022-12-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2017/11/14/00/57/christmas-2947257_960_720.jpg', max_length=300),
        ),
    ]
