# Generated by Django 4.1.3 on 2022-12-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_author_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
