# Generated by Django 4.1.3 on 2022-12-10 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('prioridad', models.IntegerField(default=3)),
            ],
        ),
    ]
