# Generated by Django 4.1.3 on 2022-12-05 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manyToOne', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
